### ISSUE TITLE
use openzeppelin Ownable instead of custom implementation

### ISSUE THREAD

**Issue by xh3b4sd** [yieldswap-protocol/yieldswap#5]
@asardon right now we use our own [custom implementation of `Ownable`](https://github.com/asardon/yieldswap/blob/a5e92eee907333a7ac49b661fa66078a40c3ac4e/src/contracts/Ownable.sol). Best practice is to leverage battle tested community standards. I would suggest to incorporate [OpenZeppelin `Ownable`](https://docs.openzeppelin.com/contracts/4.x/access-control).

**Comment by asardon** [comment]
@xh3b4sd you're right, will do

**Comment by asardon** [comment]
done
